version: '3'
services:
  django:
    build:
      context: api
    ports:
      - '8000:8000'
    volumes:
      - ./api:/code

  nodejs:
    build:
      context: soureddit
    ports:
      - '3000:3000'
    volumes:
      - ./soureddit:/app
    depends_on:
      - django