version: '3'
services:
  django:
    build:
      context: api
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: ./api
        target: /opt/app/code

  frontend:
    build:
      context: soureddit/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./soureddit/frontend
        target: /app

  backend:
    build:
      context: soureddit/backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: ./soureddit/backend
        target: /app