version: '3'
services:
  django:
    build:
      context: api
    ports:
      - '8000:8000'
    volumes:
      - ./api:/code
    environment:
      mongodb_uri: ${mongodb_uri}
      DOCKER_ENV: True
    env_file:
      - .env
    networks:
      - soureddit

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9005:9005
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - data:/data
      - config:/root/.minio
    command: ["server", "--console-address", ":9005", "/data"]
    networks:
      - soureddit

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - soureddit

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - soureddit

  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - soureddit

  init:
    image: cassandra:3.11.2
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "/init.sh" ]
    env_file:
      - .env
    volumes:
      - ./cassandra-init.sh:/init.sh
    networks:
      - soureddit

volumes:
  data:
  config:

networks:
  soureddit:
    driver: bridge
